name: Build nginx

on:
  push:
    branches: ['main']
    paths: ['images/nginx/**']
  workflow_dispatch:

jobs:
  call-build:
    uses: ./.github/workflows/_base.yaml
    with:
      image_name: nginx
      context_path: ./images/nginx
